import Head from 'next/head'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="container mx-auto">
				<h1 className="text-center">Hello Next.js</h1>
				<p className="text-center">
					This is the <strong>Create Next App</strong> example.
				</p>
			</div>
		</>
	)
}
