import Head from 'next/head'
import { useState } from 'react'
import axios from 'axios'
import SearchUser from '@comps/SearchUser'
import UserProfile from '@comps/UserProfile'
import ClanProfile from '@comps/ClanProfile'
import SelectButton from '../comps/layout/SelectButton'

export default function Home() {
	const [searchTerm, setSearchTerm] = useState('')

	const [user, setUser] = useState(null)
	const [clan, setClan] = useState(null)

	const setSearch = e => {
		setSearchTerm(e.target.value)
	}
	const submitSearch = async e => {
		e.preventDefault()
		if (searchTerm !== '') {
			const res = await axios.get(
				`api/v1/users/${
					searchTerm.includes('#')
						? encodeURIComponent(searchTerm)
						: `%23${searchTerm}`
				}`
			)
			const data = await res.data
			setUser(data)
			if (res.status == 200) {
				setSearchTerm('')
			}
		}
	}
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="container mx-auto">
				<div className="container mx-auto flex justify-between align-center my-3">
					<SelectButton flag="Player" />
					<SelectButton flag="Clan" />
				</div>
				<div className="m-16">
					<SearchUser
						submitSearch={submitSearch}
						setSearch={setSearch}
						searchTerm={searchTerm}
					/>
				</div>
				<div className="m-16">
					{user !== null && <UserProfile name={user.name} />}
					{clan !== null && <ClanProfile />}
				</div>
			</main>
		</>
	)
}
